export const PROFILE_AVATARS = [
  "Aluber the Dogmatic.png",
  "Apoqliphort Towers.png",
  "Auram the World Chalice Blademaster.png",
  "Beetrooper Sting Lancer.png",
  "Black Luster Soldier - Super Soldier.png",
  "Blackbeard, the Plunder Patroll Captain - Icon.png",
  "Condemned Darklord.png",
  "Crusadia Equimax.png",
  "Danger! Bigfoot!.png",
  "Danger! Nessie!.png",
  "Dark Magician.png",
  "Demise, Supreme King of Armageddon.png",
  "Destiny HERO - Destroyer Phoenix Enforcer.png",
  "Digital Bug Rhinosebus.png",
  "Dinomist Rex.png",
  "Dogmatika Ecclesia, the Virtuous.png",
  "Elementsaber Lapauila Mana.png",
  "Erebus the Underworld Monarch.png",
  "Fallen of Albaz.png",
  "Geargiagear Gigant XG.png",
  "Gem-Knight Master Diamond.png",
  "Ghostrick Alucard.png",
  "Gladiator Beast Domitianus.png",
  "Great Shogun Shien.png",
  "Hela, Generaider Boss of Doom.png",
  "Herald of Ultimateness.png",
  "House Dragonmaid.png",
  "Judgement Dragon.png",
  "Karakuri Super Shogun mdl 00N Bureibu.png",
  "Knightmare Gryphon.png",
  "Megalith Aratron.png",
  "Mekk-Knight Spectrum Supreme.png",
  "Myutant GB-88.png",
  "Myutant Mutant.png",
  "Nephthys, the Sacred Flame.png",
  "Oneiros, the Dream Mirror Erlking.png",
  "Oneiros, the Dream Mirror Tormentor.png",
  "Orchustrion.png",
  "PawaPuro.png",
  "Punishment Dragon.png",
  "Revendread Slayer - Icon.png",
  "Shiranui Sunsaga.png",
  "Starry Night, Starry Dragon.png",
  "Swordsoul Supreme Sovereign - Chengying.png",
  "Teardrop the Rikka Queen.png",
  "The Weather Painter Rainbow.png",
  "Thunder Dragon Colossus.png",
  "Time Thief Redoer.png",
  "True King of All Calamities.png",
  "Upstart Goblin.png",
  "Vendread Battlelord.png",
  "Vendred Chimera.png",
  "Visas Starfrost.png",
  "Warrior Dai Grepher.png",
  "X-Krawler Synaphysis.png",
  "Yuki-Onna, the Absolute Zero Mayakashi.png"
];
