-- Create the new table to handle multiple decklists per participant
CREATE TABLE public.tournament_decklists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participant_id BIGINT NOT NULL REFERENCES public.tournament_participants(id) ON DELETE CASCADE,
    deck_id BIGINT NOT NULL REFERENCES public.decks(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    UNIQUE (participant_id, deck_id)
);

-- Remove the old deck_id column from the participants table
ALTER TABLE public.tournament_participants
DROP COLUMN deck_id;

-- Add RLS policies for the new table
ALTER TABLE public.tournament_decklists ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated users to view decklists"
ON public.tournament_decklists
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Allow users to insert their own decklists"
ON public.tournament_decklists
FOR INSERT
TO authenticated
WITH CHECK (
  (SELECT user_id FROM public.tournament_participants WHERE id = participant_id) = auth.uid()
);

CREATE POLICY "Allow users to delete their own decklists"
ON public.tournament_decklists
FOR DELETE
TO authenticated
USING (
  (SELECT user_id FROM public.tournament_participants WHERE id = participant_id) = auth.uid()
);
