-- Create user_tournament_banners table
CREATE TABLE public.user_tournament_banners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    tournament_id BIGINT REFERENCES public.tournaments(id) ON DELETE SET NULL,
    banner_url TEXT NOT NULL,
    title TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Enable Row Level Security for user_tournament_banners
ALTER TABLE public.user_tournament_banners ENABLE ROW LEVEL SECURITY;

-- Policy for authenticated users to insert their own banners
CREATE POLICY "Allow authenticated users to insert their own banners"
ON public.user_tournament_banners FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- Policy for authenticated users to select their own banners and public banners
CREATE POLICY "Allow authenticated users to select their own banners and public banners"
ON public.user_tournament_banners FOR SELECT
USING (true); -- All banners are public for viewing on profiles

-- Policy for authenticated users to update their own banners
CREATE POLICY "Allow authenticated users to update their own banners"
ON public.user_tournament_banners FOR UPDATE
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- Policy for authenticated users to delete their own banners
CREATE POLICY "Allow authenticated users to delete their own banners"
ON public.user_tournament_banners FOR DELETE
USING (auth.uid() = user_id);

-- Grant permissions to authenticated role
GRANT ALL ON public.user_tournament_banners TO authenticated;
GRANT ALL ON SEQUENCE public.user_tournament_banners_id_seq TO authenticated;
