-- Add parent_comment_id for replies
ALTER TABLE public.deck_comments
ADD COLUMN parent_comment_id BIGINT REFERENCES public.deck_comments(id) ON DELETE CASCADE;

ALTER TABLE public.news_comments
ADD COLUMN parent_comment_id BIGINT REFERENCES public.news_comments(id) ON DELETE CASCADE;

-- Create table for deck comment likes
CREATE TABLE public.deck_comment_likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id BIGINT NOT NULL REFERENCES public.deck_comments(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE (comment_id, user_id)
);

-- Create table for news comment likes
CREATE TABLE public.news_comment_likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id BIGINT NOT NULL REFERENCES public.news_comments(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE (comment_id, user_id)
);

-- RLS for deck_comment_likes
ALTER TABLE public.deck_comment_likes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" ON public.deck_comment_likes FOR SELECT USING (true);
CREATE POLICY "Allow authenticated users to like" ON public.deck_comment_likes FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Allow user to unlike" ON public.deck_comment_likes FOR DELETE USING (auth.uid() = user_id);

-- RLS for news_comment_likes
ALTER TABLE public.news_comment_likes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" ON public.news_comment_likes FOR SELECT USING (true);
CREATE POLICY "Allow authenticated users to like" ON public.news_comment_likes FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Allow user to unlike" ON public.news_comment_likes FOR DELETE USING (auth.uid() = user_id);
