-- Notification type ENUM
CREATE TYPE public.notification_type AS ENUM (
    'new_deck_comment',
    'new_news_comment',
    'new_comment_reply',
    'new_deck_like',
    'new_news_like',
    'new_comment_like',
    'new_clan_member'
);

-- Notifications table
CREATE TABLE public.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    type public.notification_type NOT NULL,
    data JSONB,
    link TEXT,
    is_read BOOLEAN DEFAULT false NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- RLS for notifications
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can only see their own notifications"
ON public.notifications
FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can update their own notifications (mark as read)"
ON public.notifications
FOR UPDATE USING (auth.uid() = user_id);

-- Enable realtime on the notifications table
ALTER PUBLICATION supabase_realtime ADD TABLE public.notifications;
