-- Create the tournament_participants table
CREATE TABLE public.tournament_participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    tournament_id BIGINT REFERENCES public.tournaments(id) ON DELETE CASCADE,
    total_wins_in_tournament INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (user_id, tournament_id)
);

-- Enable Row Level Security
ALTER TABLE public.tournament_participants ENABLE ROW LEVEL SECURITY;

-- RLS Policies for tournament_participants
CREATE POLICY "Allow public read access to participants"
ON public.tournament_participants
FOR SELECT
USING (true);

CREATE POLICY "Allow users to insert their own participation"
ON public.tournament_participants
FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Allow admins and organizers to update wins"
ON public.tournament_participants
FOR UPDATE
USING (get_user_role() IN ('admin', 'organizer'))
WITH CHECK (get_user_role() IN ('admin', 'organizer'));

-- Create the player_rankings_view
CREATE OR REPLACE VIEW public.player_rankings_view AS
SELECT
  p.id AS user_id,
  p.username,
  p.avatar_url,
  COALESCE(SUM(tp.total_wins_in_tournament), 0) AS total_wins,
  (COALESCE(SUM(tp.total_wins_in_tournament), 0) * 5) AS total_points
FROM
  public.profiles p
LEFT JOIN
  public.tournament_participants tp ON p.id = tp.user_id
GROUP BY
  p.id, p.username, p.avatar_url
ORDER BY
  total_points DESC;
