-- Add configuration column to tournaments
ALTER TABLE public.tournaments 
ADD COLUMN banishment_count INTEGER DEFAULT 0;

-- Create table to store the banned cards per tournament/user
CREATE TABLE public.tournament_banned_cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tournament_id BIGINT REFERENCES public.tournaments(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    card_id TEXT REFERENCES public.cards(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index for faster lookups
CREATE INDEX idx_tournament_banned_cards_tournament_id ON public.tournament_banned_cards(tournament_id);

-- RPC to register a player AND submit their bans transactionally
CREATE OR REPLACE FUNCTION public.register_with_bans(
    p_tournament_id BIGINT, 
    p_user_id UUID, 
    p_card_ids TEXT[],
    p_team_selection TEXT DEFAULT NULL
) 
RETURNS VOID 
LANGUAGE plpgsql 
SECURITY DEFINER
AS $$
BEGIN
    -- 1. Check if tournament exists and is open
    IF NOT EXISTS (SELECT 1 FROM tournaments WHERE id = p_tournament_id) THEN
        RAISE EXCEPTION 'Tournament not found';
    END IF;

    -- 2. Check if user is already enrolled
    IF EXISTS (SELECT 1 FROM tournament_participants WHERE tournament_id = p_tournament_id AND user_id = p_user_id) THEN
        RAISE EXCEPTION 'User already enrolled';
    END IF;

    -- 3. Register user in participants
    INSERT INTO tournament_participants (tournament_id, user_id, team_selection)
    VALUES (p_tournament_id, p_user_id, p_team_selection);

    -- 4. Insert banned cards
    IF array_length(p_card_ids, 1) > 0 THEN
        INSERT INTO tournament_banned_cards (tournament_id, user_id, card_id)
        SELECT p_tournament_id, p_user_id, unnest(p_card_ids);
    END IF;
END;
$$;

-- RPC to get the consolidated banlist for a tournament
CREATE OR REPLACE FUNCTION public.get_tournament_banlist(p_tournament_id BIGINT)
RETURNS TABLE (
    card_id TEXT,
    name TEXT,
    image_url_small TEXT,
    count BIGINT
) 
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        tbc.card_id,
        c.name,
        c.image_url_small,
        COUNT(tbc.card_id) as count
    FROM 
        tournament_banned_cards tbc
    JOIN 
        cards c ON tbc.card_id = c.id
    WHERE 
        tbc.tournament_id = p_tournament_id
    GROUP BY 
        tbc.card_id, c.name, c.image_url_small
    ORDER BY 
        count DESC, c.name ASC;
END;
$$;
