-- 1. Add equipped_frame_url to profiles table
ALTER TABLE public.profiles
ADD COLUMN equipped_frame_url TEXT;

-- 2. Create user_unlocked_frames table
CREATE TABLE public.user_unlocked_frames (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    frame_url TEXT NOT NULL,
    unlocked_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT user_unlocked_frames_user_id_frame_url_key UNIQUE (user_id, frame_url)
);

-- Enable RLS
ALTER TABLE public.user_unlocked_frames ENABLE ROW LEVEL SECURITY;

-- Policies for user_unlocked_frames
CREATE POLICY "Users can view their own unlocked frames"
ON public.user_unlocked_frames FOR SELECT
USING (auth.uid() = user_id);

-- 3. Create a table to map levels to frame rewards
CREATE TABLE public.frame_rewards (
    level_required INT PRIMARY KEY,
    frame_url TEXT NOT NULL UNIQUE
);

-- No RLS needed for this table, it's public static data.

-- 4. Insert the frame reward data
INSERT INTO public.frame_rewards (level_required, frame_url) VALUES
(1, '/borders/leveling/beginners_frame.png'),
(2, '/borders/leveling/bronze_frame.png'),
(5, '/borders/leveling/silver_frame.png'),
(10, '/borders/leveling/gold_frame.png'),
(15, '/borders/leveling/platinum_frame.png'),
(20, '/borders/leveling/diamond_frame.png'),
(25, '/borders/leveling/master_frame.png'),
(30, '/borders/leveling/green_frame.png'),
(40, '/borders/leveling/mint_frame.png'),
(50, '/borders/leveling/orange_frame.png'),
(60, '/borders/leveling/red_frame.png'),
(70, '/borders/leveling/pink_frame.png'),
(80, '/borders/leveling/purple_frame.png'),
(90, '/borders/leveling/navy_frame.png'),
(100, '/borders/leveling/blue_frame.png');

-- 5. Modify recalculate_player_level to unlock frames
CREATE OR REPLACE FUNCTION public.recalculate_player_level(p_user_id uuid)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
DECLARE
  current_xp INT;
  new_level INT;
  old_level INT;
  reward_frame_url TEXT;
BEGIN
  -- Get the user's current total XP and old level
  SELECT xp, level INTO current_xp, old_level FROM public.profiles WHERE id = p_user_id;

  -- Ensure XP is not negative
  IF current_xp < 0 THEN
    current_xp := 0;
  END IF;

  -- Calculate the new level based on cumulative XP
  new_level := floor(current_xp / 50) + 1;

  -- Update the profile with the new level and the (potentially floored) XP
  UPDATE public.profiles
  SET 
    level = new_level,
    xp = current_xp -- Ensure XP is set to 0 if it was negative
  WHERE id = p_user_id;

  -- If the user leveled up, check for new frame rewards
  IF new_level > old_level THEN
    FOR reward_frame_url IN
      SELECT fr.frame_url
      FROM public.frame_rewards fr
      WHERE fr.level_required > old_level AND fr.level_required <= new_level
    LOOP
      -- Insert the new frame into the user's unlocked frames, ignoring if it already exists
      INSERT INTO public.user_unlocked_frames (user_id, frame_url)
      VALUES (p_user_id, reward_frame_url)
      ON CONFLICT (user_id, frame_url) DO NOTHING;
    END LOOP;
  END IF;

  -- Automatically unlock the beginner frame for everyone
  INSERT INTO public.user_unlocked_frames (user_id, frame_url)
  VALUES (p_user_id, '/borders/leveling/beginners_frame.png')
  ON CONFLICT (user_id, frame_url) DO NOTHING;
  
END;
$function$;

-- 6. Create the equip_frame RPC function
CREATE OR REPLACE FUNCTION public.equip_frame(p_frame_url TEXT)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
BEGIN
  -- Check if the user has unlocked this frame
  IF NOT EXISTS (
    SELECT 1
    FROM public.user_unlocked_frames uuf
    WHERE uuf.user_id = auth.uid() AND uuf.frame_url = p_frame_url
  ) THEN
    -- Also check for admin frames which are not in the rewards table
    IF p_frame_url NOT LIKE '/borders/adm/%' OR (
      SELECT role FROM public.profiles WHERE id = auth.uid()
    ) NOT IN ('admin', 'organizer') THEN
      RAISE EXCEPTION 'You have not unlocked this frame.';
    END IF;
  END IF;

  -- Update the user's equipped frame
  UPDATE public.profiles
  SET equipped_frame_url = p_frame_url
  WHERE id = auth.uid();
END;
$function$;
