--------------------------------------------------------------------------------
-- GLOBAL CHAT SYSTEM
--------------------------------------------------------------------------------

-- 1. Criar a tabela de mensagens globais
CREATE TABLE IF NOT EXISTS public.global_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT content_not_empty CHECK (length(trim(content)) > 0),
    CONSTRAINT content_length CHECK (length(content) <= 500)
);

-- 2. Habilitar RLS
ALTER TABLE public.global_messages ENABLE ROW LEVEL SECURITY;

-- 3. Políticas de Segurança
-- Qualquer um pode ler as mensagens
CREATE POLICY "Anyone can view global messages"
ON public.global_messages FOR SELECT
TO public
USING (true);

-- Usuários autenticados podem enviar mensagens
CREATE POLICY "Authenticated users can send messages"
ON public.global_messages FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

-- Apenas Admins e Super-Admins podem deletar mensagens (Moderação)
CREATE POLICY "Admins can delete messages"
ON public.global_messages FOR DELETE
TO authenticated
USING (
    public.is_admin() OR 
    auth.uid() = '80193776-6790-457c-906d-ed45ea16df9f'::uuid
);

-- 4. Habilitar Realtime para esta tabela
-- No self-hosted, precisamos garantir que a tabela esteja na publicação do realtime
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' 
    AND schemaname = 'public' 
    AND tablename = 'global_messages'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.global_messages;
  END IF;
END $$;

-- 5. Index para performance nas buscas recentes
CREATE INDEX IF NOT EXISTS idx_global_messages_created_at ON public.global_messages (created_at DESC);
