-- Create Sweepstakes (Bolões) table
CREATE TABLE IF NOT EXISTS public.sweepstakes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    description text,
    entry_fee numeric(10,2) NOT NULL DEFAULT 5.00,
    start_date timestamp with time zone NOT NULL, -- When betting opens
    end_date timestamp with time zone NOT NULL, -- When betting closes (deadline)
    rules jsonb DEFAULT '{}'::jsonb,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create Divisions table (Links Sweepstake to Tournaments)
-- Example: Division 1 -> Tournament ID 105
CREATE TABLE IF NOT EXISTS public.sweepstake_divisions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sweepstake_id bigint REFERENCES public.sweepstakes(id) ON DELETE CASCADE,
    tournament_id bigint REFERENCES public.tournaments(id) ON DELETE SET NULL, -- Can be null if tournament not created yet
    division_name text NOT NULL, -- "Divisão 1", "Divisão 2", etc.
    points_reward int NOT NULL DEFAULT 10, -- 10, 15, 20, 25
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create Bets table (The User's entry)
CREATE TABLE IF NOT EXISTS public.sweepstake_bets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sweepstake_id bigint REFERENCES public.sweepstakes(id) ON DELETE CASCADE,
    user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    
    -- Payment Info
    payment_status text NOT NULL DEFAULT 'pending' CHECK (payment_status IN ('pending', 'paid', 'failed', 'refunded')),
    payment_method text, -- 'mercadopago', 'paypal', 'manual'
    transaction_id text, -- External ID from MP/PayPal
    payment_amount numeric(10,2),
    
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,

    -- Ensure one bet per user per sweepstake
    CONSTRAINT unique_user_bet_per_sweepstake UNIQUE (sweepstake_id, user_id)
);

-- Create Picks table (The specific predictions)
CREATE TABLE IF NOT EXISTS public.sweepstake_picks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bet_id bigint REFERENCES public.sweepstake_bets(id) ON DELETE CASCADE,
    division_id bigint REFERENCES public.sweepstake_divisions(id) ON DELETE CASCADE,
    predicted_winner_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL, -- The player they bet on
    
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    -- Ensure one pick per division per bet
    CONSTRAINT unique_pick_per_division UNIQUE (bet_id, division_id)
);

-- Enable RLS
ALTER TABLE public.sweepstakes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sweepstake_divisions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sweepstake_bets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sweepstake_picks ENABLE ROW LEVEL SECURITY;

-- RLS Policies

-- Sweepstakes: Visible to everyone
CREATE POLICY "Sweepstakes are viewable by everyone" ON public.sweepstakes FOR SELECT USING (true);
CREATE POLICY "Admins can manage sweepstakes" ON public.sweepstakes FOR ALL USING (
  auth.uid() IN (SELECT id FROM public.profiles WHERE role IN ('admin', 'organizer'))
);

-- Divisions: Visible to everyone
CREATE POLICY "Divisions are viewable by everyone" ON public.sweepstake_divisions FOR SELECT USING (true);
CREATE POLICY "Admins can manage divisions" ON public.sweepstake_divisions FOR ALL USING (
  auth.uid() IN (SELECT id FROM public.profiles WHERE role IN ('admin', 'organizer'))
);

-- Bets:
-- Users can see their own bets.
-- Everyone can see CONFIRMED bets IF the betting period is closed (Transparency Rule).
-- Admins can see all bets.
CREATE POLICY "Users can see own bets" ON public.sweepstake_bets FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Public can see confirmed bets after deadline" ON public.sweepstake_bets FOR SELECT USING (
    payment_status = 'paid' AND
    EXISTS (
        SELECT 1 FROM public.sweepstakes s 
        WHERE s.id = sweepstake_id 
        AND now() > s.end_date
    )
);

CREATE POLICY "Admins see all bets" ON public.sweepstake_bets FOR SELECT USING (
    auth.uid() IN (SELECT id FROM public.profiles WHERE role IN ('admin', 'organizer'))
);

CREATE POLICY "Users can create bets" ON public.sweepstake_bets FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Only Admins or System (Service Role) can update payment status
-- Users should NOT be able to update their bet to 'paid' manually
CREATE POLICY "Admins update bets" ON public.sweepstake_bets FOR UPDATE USING (
    auth.uid() IN (SELECT id FROM public.profiles WHERE role IN ('admin', 'organizer'))
);

-- Picks:
-- Inherits visibility from Bets mostly, but strictly controlled
CREATE POLICY "Users see own picks" ON public.sweepstake_picks FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.sweepstake_bets b WHERE b.id = bet_id AND b.user_id = auth.uid())
);

CREATE POLICY "Public see confirmed picks after deadline" ON public.sweepstake_picks FOR SELECT USING (
    EXISTS (
        SELECT 1 FROM public.sweepstake_bets b
        JOIN public.sweepstakes s ON b.sweepstake_id = s.id
        WHERE b.id = bet_id
        AND b.payment_status = 'paid'
        AND now() > s.end_date
    )
);

CREATE POLICY "Admins see all picks" ON public.sweepstake_picks FOR SELECT USING (
    auth.uid() IN (SELECT id FROM public.profiles WHERE role IN ('admin', 'organizer'))
);

CREATE POLICY "Users insert picks via RPC only usually, but allowing insert if they own the bet" ON public.sweepstake_picks FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM public.sweepstake_bets b WHERE b.id = bet_id AND b.user_id = auth.uid())
);
