-- Create tournament_matches table
CREATE TABLE IF NOT EXISTS public.tournament_matches (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tournament_id bigint REFERENCES public.tournaments(id) ON DELETE CASCADE,
    player1_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    player2_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    winner_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    round_name text, -- e.g., "Round 1", "Top 8", "Final"
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS Policies
ALTER TABLE public.tournament_matches ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read access" ON public.tournament_matches
    FOR SELECT USING (true);

CREATE POLICY "Organizers and Admins can insert matches" ON public.tournament_matches
    FOR INSERT WITH CHECK (
        auth.role() = 'authenticated' AND 
        public.get_user_role() IN ('admin', 'organizer')
    );

CREATE POLICY "Organizers and Admins can update matches" ON public.tournament_matches
    FOR UPDATE USING (
        auth.role() = 'authenticated' AND 
        public.get_user_role() IN ('admin', 'organizer')
    );

CREATE POLICY "Organizers and Admins can delete matches" ON public.tournament_matches
    FOR DELETE USING (
        auth.role() = 'authenticated' AND 
        public.get_user_role() IN ('admin', 'organizer')
    );

-- RPC to get rivalry history between two players
CREATE OR REPLACE FUNCTION get_rivalry_history(p_player1_id uuid, p_player2_id uuid)
RETURNS TABLE (
    id bigint,
    tournament_title text,
    tournament_date date,
    round_name text,
    winner_id uuid,
    winner_name text,
    winner_avatar text
) 
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        m.id,
        t.title as tournament_title,
        t.event_date as tournament_date,
        m.round_name,
        m.winner_id,
        p.username as winner_name,
        p.avatar_url as winner_avatar
    FROM 
        public.tournament_matches m
    JOIN 
        public.tournaments t ON m.tournament_id = t.id
    LEFT JOIN 
        public.profiles p ON m.winner_id = p.id
    WHERE 
        (m.player1_id = p_player1_id AND m.player2_id = p_player2_id)
        OR
        (m.player1_id = p_player2_id AND m.player2_id = p_player1_id)
    ORDER BY 
        t.event_date DESC, m.created_at DESC;
END;
$$;