-- 1. Create table for user titles (inventory)
CREATE TABLE public.user_titles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    title TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS for user_titles
ALTER TABLE public.user_titles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own titles"
ON public.user_titles FOR SELECT
USING (auth.uid() = user_id);

-- Admins can do anything
CREATE POLICY "Admins can manage user_titles"
ON public.user_titles FOR ALL
USING (
  EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role IN ('admin', 'organizer')
  )
);

-- 2. Add equipped_titles column to profiles (Max 3, handled by app logic/RPC)
ALTER TABLE public.profiles
ADD COLUMN equipped_titles TEXT[] DEFAULT '{}';

-- 3. RPC to grant a title (Admin only)
CREATE OR REPLACE FUNCTION public.grant_title(p_user_id UUID, p_title TEXT)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
BEGIN
  -- Check if caller is admin/organizer
  IF (SELECT role FROM public.profiles WHERE id = auth.uid()) NOT IN ('admin', 'organizer') THEN
    RAISE EXCEPTION 'Only admins can grant titles.';
  END IF;

  -- Insert title if not exists (allow duplicates? No, unique title per user seems better)
  IF NOT EXISTS (SELECT 1 FROM public.user_titles WHERE user_id = p_user_id AND title = p_title) THEN
    INSERT INTO public.user_titles (user_id, title)
    VALUES (p_user_id, p_title);
  ELSE
    RAISE NOTICE 'User already has this title.';
  END IF;
END;
$function$;

-- 4. RPC to equip titles (User self-service)
CREATE OR REPLACE FUNCTION public.equip_titles(p_titles TEXT[])
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
DECLARE
  t text;
BEGIN
  -- 1. Validate number of titles
  IF array_length(p_titles, 1) > 3 THEN
    RAISE EXCEPTION 'You can only equip up to 3 titles.';
  END IF;

  -- 2. Validate user owns all titles
  IF p_titles IS NOT NULL THEN
    FOREACH t IN ARRAY p_titles
    LOOP
      IF NOT EXISTS (
        SELECT 1 FROM public.user_titles 
        WHERE user_id = auth.uid() AND title = t
      ) THEN
        RAISE EXCEPTION 'You do not own the title: %', t;
      END IF;
    END LOOP;
  END IF;

  -- 3. Update profile
  UPDATE public.profiles
  SET equipped_titles = COALESCE(p_titles, '{}')
  WHERE id = auth.uid();
END;
$function$;
